version: "3.9"

services:
  s3api:
    container_name: s3api
    build:
      context: .
      target: dev
    ports:
      - "5005:5005"
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - s3_net

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z.fips
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./.data/minio:/data
    networks:
      - s3_net

networks:
  s3_net:
    driver: bridge
