# papigoplug-test.yml

name: s3api-unit-test
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  papigoplug-test-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2
        id: go

      - name: Install Packages
        run: go get -v -t -d ./...

      - name: Run Tests
        run: go test ./auth ./blobstore -tags=test -v
